// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-WX8q14qPqC7Xq1HEgnr_2PBce8W3oJQ',
    appId: '1:146443206704:web:138b3d6d7a1ad59b48adf5',
    messagingSenderId: '146443206704',
    projectId: 'shopping-app-31f98',
    authDomain: 'shopping-app-31f98.firebaseapp.com',
    storageBucket: 'shopping-app-31f98.firebasestorage.app',
    measurementId: 'G-CEQCRD7KRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclsm4HgCcyTOugNOSnB71j_d2oq9hj_4',
    appId: '1:146443206704:android:9127ca1ec4575ca348adf5',
    messagingSenderId: '146443206704',
    projectId: 'shopping-app-31f98',
    storageBucket: 'shopping-app-31f98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9m2JFXnqeoT4SkHg7VcfV59mzjb6RBcc',
    appId: '1:146443206704:ios:7f9cb3c323e72ed548adf5',
    messagingSenderId: '146443206704',
    projectId: 'shopping-app-31f98',
    storageBucket: 'shopping-app-31f98.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9m2JFXnqeoT4SkHg7VcfV59mzjb6RBcc',
    appId: '1:146443206704:ios:7f9cb3c323e72ed548adf5',
    messagingSenderId: '146443206704',
    projectId: 'shopping-app-31f98',
    storageBucket: 'shopping-app-31f98.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-WX8q14qPqC7Xq1HEgnr_2PBce8W3oJQ',
    appId: '1:146443206704:web:a10a2c7cedb3630848adf5',
    messagingSenderId: '146443206704',
    projectId: 'shopping-app-31f98',
    authDomain: 'shopping-app-31f98.firebaseapp.com',
    storageBucket: 'shopping-app-31f98.firebasestorage.app',
    measurementId: 'G-DG9CK62B5M',
  );

}